package com.freya02.bot.tag;

//TODO make this class accept a reason string, this will be sent to the discord user
// Exceptions should be generated by TagDB not by the command code
// Apply stack trace optimizations
public class TagException extends RuntimeException {
	public TagException(String message) {
		super(message, null, true, false);
	}
}
