package dev.freya02.doxxy.docs.utils

import dev.freya02.doxxy.docs.declarations.JavadocMethod
import dev.freya02.doxxy.docs.exceptions.DocParseException
import org.jsoup.nodes.Document
import org.jsoup.nodes.Element

internal object DocUtils {

    fun getSimpleSignature(elementId: String): String {
        return StringBuilder().apply {
            val index = elementId.indexOf('(')
            append(elementId, 0, index)

            val simpleParameters = elementId.substring(index + 1, elementId.length - 1).split(",")
                .filter { parameter -> parameter.isNotBlank() }
                .joinToString(
                    prefix = "(",
                    postfix = ")",
                    separator = ", "
                ) { parameter -> DecomposedName.getSimpleClassName(parameter.trim()) }

            append(simpleParameters)
        }.toString()
    }

    fun getSimpleAnnotatedSignature(method: JavadocMethod) = buildString(100) {
        method.methodAnnotations?.let { appendLine(it) }

        if (method.isStatic) append("static ")
        // Use the class name where the method was declared from,
        // using the class name which inherited this method is undesirable
        // because javadocs are shared with inheritors
        append(method.className)
        append("#")
        append(method.methodName)

        append(method.parameters.joinToString(", ", "(", ")") { parameter ->
            val annotations = buildString {
                val annotations = parameter.annotations
                if (annotations.isNotEmpty()) {
                    append(parameter.annotations.joinToString(" ") { "@$it" })
                    append(" ")
                }
            }
            "$annotations${parameter.simpleType} ${parameter.name}"
        })

        append(" : ")
        append(method.returnType.removeAnnotations())
    }

    fun Document.isJavadocVersionCorrect(): Boolean {
        val head: Element = selectFirst("head") ?: throw DocParseException("Javadoc at '${baseUri()}' is not javadoc 17")
        val nodes = head.childNodes()
        if (nodes.size < 2) return false

        val secondComment = nodes[1].attr("#comment")
        return "Generated by javadoc (17)" in secondComment
    }
}
