package com.freya02.docs.utils

import com.freya02.docs.DocParseException
import org.jsoup.nodes.Document
import org.jsoup.nodes.Element

@Suppress("NOTHING_TO_INLINE")
inline fun requireDoc(boolean: Boolean) {
    if (!boolean)
        throw DocParseException()
}

fun Document.checkJavadocVersion(sourceURL: String) {
    val head: Element = selectFirst("head") ?: throw DocParseException("Javadoc at '$sourceURL' is not javadoc 17")
    val nodes = head.childNodes()
    if (nodes.size < 2) throw DocParseException("Javadoc at '$sourceURL' is not javadoc 17")
    if ("Generated by javadoc (17)" !in nodes[1].attr("#comment")) throw DocParseException("Javadoc at '$sourceURL' is not javadoc 17")
}