package com.freya02.docs;

import com.freya02.bot.utils.DecomposedName;
import org.jetbrains.annotations.NotNull;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;

import java.util.List;
import java.util.StringJoiner;

public class DocUtils {
	@NotNull
	public static String getSimpleSignature(@NotNull String elementId) {
		final StringBuilder simpleSignatureBuilder = new StringBuilder();

		final int index = elementId.indexOf('(');
		simpleSignatureBuilder.append(elementId, 0, index);

		final StringJoiner parameterJoiner = new StringJoiner(", ", "(", ")");
		final String[] parameters = elementId.substring(index + 1, elementId.length() - 1).split(",");
		for (String parameter : parameters) {
			if (parameter.isBlank()) continue;

			final String className = DecomposedName.getSimpleClassName(parameter.trim());

			parameterJoiner.add(className);
		}

		simpleSignatureBuilder.append(parameterJoiner);

		return simpleSignatureBuilder.toString();
	}

	@SuppressWarnings("BooleanMethodIsAlwaysInverted")
	public static boolean isJavadocVersionCorrect(@NotNull Document document) {
		final Element head = document.selectFirst("head");
		if (head == null) return false;

		final List<Node> nodes = head.childNodes();
		if (nodes.size() < 2) return false;

		return nodes.get(1).attr("#comment").contains("Generated by javadoc (17)");
	}
}
